# Generated by Django 4.1.7 on 2023-05-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sectioninf',
        ),
    ]
