# Generated by Django 4.1.7 on 2023-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_experience_item_experience_f_item_lessoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='officePC_E',
            field=models.CharField(choices=[('Excel', 'Excel'), ('Word', 'Word'), ('PowerPoint', 'PowerPoint'), ('Access', 'Access'), ('Google SpreadSheet', 'Google SpreadSheet'), ('GoogleDocs', 'GoogleDocs')], default=None, max_length=200, verbose_name='業務経験アプリケーション'),
        ),
        migrations.AddField(
            model_name='item',
            name='officePC_T',
            field=models.CharField(choices=[('Excel', 'Excel'), ('Word', 'Word'), ('PowerPoint', 'PowerPoint'), ('Access', 'Access'), ('Google SpreadSheet', 'Google SpreadSheet'), ('GoogleDocs', 'GoogleDocs')], default=None, max_length=200, verbose_name='使用可能アプリケーション'),
        ),
        migrations.AlterField(
            model_name='item',
            name='officePC_L',
            field=models.CharField(choices=[('Excel', 'Excel'), ('Word', 'Word'), ('PowerPoint', 'PowerPoint'), ('Access', 'Access'), ('Google SpreadSheet', 'Google SpreadSheet'), ('GoogleDocs', 'GoogleDocs')], default=None, max_length=200, verbose_name='勉強中アプリケーション'),
        ),
    ]
